import networkx as nx
import matplotlib.pyplot as plt
G = nx.DiGraph()
G.add_node("metric_engagement_score")
G.add_node("metric_clv")
G.add_node("metric_product_affinity")
G.add_node("metric_recent_purchase_recency")
G.add_node("metric_aov")
G.add_node("repeat_purchase_rate")
G.add_node("metric_campaign_conversion")
G.add_node("metric_customer_retention_rate")
G.add_node("metric_engagement_channel_effectiveness")
G.add_node("metric_churn_rate")
G.add_node("metric_arpu")
G.add_edge("metric_engagement_score", "metric_clv")
G.add_edge("metric_product_affinity", "metric_clv")
G.add_edge("metric_recent_purchase_recency", "repeat_purchase_rate")
G.add_edge("metric_aov", "metric_clv")
G.add_edge("repeat_purchase_rate", "metric_clv")
G.add_edge("metric_campaign_conversion", "metric_customer_retention_rate")
G.add_edge("metric_engagement_channel_effectiveness", "metric_campaign_conversion")
G.add_edge("metric_customer_retention_rate", "metric_clv")
G.add_edge("metric_churn_rate", "metric_arpu")
G.add_edge("metric_arpu", "metric_clv")
pos = nx.spring_layout(G)
plt.figure(figsize=(10,8))
nx.draw(G, pos, with_labels=True, node_size=1500, node_color='lightblue', linewidths=2, font_size=12, arrowsize=20)
plt.show()